[package]
name = "pg_migrate_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = { version = "0.19", features = ["with-chrono-0_4"] }

[build-dependencies]
